export const blogList = [
  {
    id: 1,
    title:
      "Risus pulvinar placerat eget cras mattis cursus. Odio pretium malesuada aliquet habitasse. Fusce vitae, risus vulputate ut libero nascetur blandit quam potenti.",
    category: "news",
    description: "Non senectus odio ut ac nulla vestibulum. Bibendum risus ac ut ullamcorper. Vitae, lectus phasellus tristique mauris id eget.",
    createdAt: "July 19, 2022",
    cover: "../assets/images/chineseflag.png",
  },
  {
    id: 2,
    title: "Senectus tincidunt luctus placerat ac nibh facilisi mi. Id dolor in mauris, pharetra, commodo. Dui et morbi a tortor condimentum nulla at ullamcorper male.",
    category: "news",
    description: "Sed sit risus purus a augue eget consequat sit purus. Eget sed vitae diam hac quisque urna, nullam tristique erat. Molestie amet.",
    createdAt: "Mar 9, 2022",
    cover: "../assets/images/bman.png",
  },
  {
    id: 3,
    title: "Quam porta aenean sapien a vestibulum orci gravida. Sit tristique dolor tortor lectus natoque vitae fermentum pellentesque. Auctor suspendisse pellentesque est nec.",
    category: "politics",
    description: "Non senectus odio ut ac nulla vestibulum. Bibendum risus ac ut ullamcorper. Vitae, lectus phasellus tristique mauris id eget.",
    createdAt: "Mar 2, 2022",
    cover: "./assets/images/flag.png",
  },
  {
    id: 4,
    title: "Imperdiet pretium lectus at tincidunt pellentesque. Velit tristique id magna semper lacus elementum arcu diam urna. Turpis dolor mauris pretium augue euismo.", 
    category: "entertainment",
    description: "Eget rhoncus viverra aliquet porta in nisl. Elit bibendum elit eu dictum metus vitae, dolor id. Ipsum duis leo ipsum nam.",
    createdAt: "jun 2, 2022",
    cover: "./assets/images/reporter.png",
  },
  {
    id: 5,
    title: "Blandit eget at turpis elit non etiam eget. Ridiculus pulvinar scelerisque cum nunc fames nisl. Aliquam etiam blandit placerat amet posuere urna, erat. Mauris est hen.",
    category: "sports",
    description: "Eu orci erat ac amet, elementum. Porttitor ultrices lorem velit non risus. Dignissim diam fringilla eu penatibus elementumt.",
    createdAt: "Jun 4, 2020",
    cover: "./assets/images/sonia.png",
  },
  {
    id: 6,
    title: "Urna vitae, tempor, morbi commodo sit nisi. Eu egestas platea porttitor in malesuada pulvinar. Maecenas vel pellentesque ultrices eu lectus varius plate.",
    category: "education",
    description: "Nisl enim pellentesque diam tincidunt eu eget congue leo eget. Et tempor arcu risus sem gravida elit ut sollicitudin integer. Morbi",
    createdAt: "july 14, 2022",
    cover: "./assets/images/elaine.png",
  },
];
